import os
import torch

SEED = 42
DATA_PATH = "Train_Sequences.fasta"
EMBEDDING_PATH = "protein_esm.pkl"
MODEL_SAVE_DIR = "checkpoints"

ONLY_POSITIVE = True

AMINO_ACIDS = "ACDEFGHIKLMNPQRSTVWY"
EOS_IDX = 20
PAD_IDX = 21
MASK_IDX = 22
X_IDX = 23
VOCAB_SIZE = 24
OUT_CLASSES = 21

PEPTIDE_LENGTH = 51

T_STEPS = 100
T_SAMPLE_MIN = 0
T_SAMPLE_MAX = 99

D_MODEL = 256
NUM_LAYERS = 4
NHEAD = 8
DROPOUT = 0.1
MEMORY_LENGTH = 16
EMBEDDING_DIM = 1280

BATCH_SIZE = 64
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5
WARMUP_STEPS = 500
TOTAL_STEPS = 15000
EPOCHS = 100

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

os.makedirs(MODEL_SAVE_DIR, exist_ok=True)
